version: "3.8"

services:
  db:
    image: postgres:15
    platform: linux/amd64
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
      POSTGRES_DB: blog_api_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  web:
    build: .
    command: bash -c "bundle exec rails db:prepare && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://blog_user:blog_password@db:5432/blog_api_development
      REDIS_URL: redis://redis:6379/1

  worker:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://blog_user:blog_password@db:5432/blog_api_development
      REDIS_URL: redis://redis:6379/1

volumes:
  pgdata:
